name: Run benchmarks
on:
  push:
    tags:
      - 'test*'
jobs:
  build:
    name: Run benchmark
    runs-on: [self-hosted, bench]
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set env
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "REPO=helm" >> $GITHUB_ENV
          echo "http_proxy=http://localhost:3128" >> $GITHUB_ENV
          echo "https_proxy=http://localhost:3128" >> $GITHUB_ENV
      - name: Run target benchmark
        run: |
          git clone https://github.com/artipie/benchmarks.git tmp-bench
          cd tmp-bench/adapters
          make run TARGET=${{ env.REPO }}
          mkdir -p $GITHUB_WORKSPACE/benchmarks/results/${{ env.TAG }}
          cp -avr out/${{ env.REPO }}/* $GITHUB_WORKSPACE/benchmarks/results/${{ env.TAG }}
          cd ../..
          rm -rf tmp-bench
      - name: Commit and push results
        run: |
          git config --global user.name "github-action"
          git config --global user.email "benchmarks@artipie.com"
          git add .
          git commit -m "bench: added results of benchmarks to readme (through action)"
          git push origin HEAD:master
