name: Run benchmarks
on:
  push:
    tags:
      - 'test*'
jobs:
  build:
    name: Run benchmark
    runs-on: [self-hosted, bench]
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set env
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "REPO=helm" >> $GITHUB_ENV
          echo "http_proxy=http://localhost:3128" >> $GITHUB_ENV
          echo "https_proxy=http://localhost:3128" >> $GITHUB_ENV
      - name: Run target benchmark
        run: |
          mkdir -p $GITHUB_WORKSPACE/benchmarks/results/${{ env.TAG }}
#          git clone https://github.com/artipie/benchmarks.git tmp-bench
#          cd tmp-bench/adapters
#          make run TARGET=${{ env.REPO }}
#          mkdir -p $GITHUB_WORKSPACE/benchmarks/results/${{ env.TAG }}
#          cp -avr out/${{ env.REPO }}/* $GITHUB_WORKSPACE/benchmarks/results/${{ env.TAG }}
#          cd ../..
#          rm -rf tmp-bench
      - name: Set user and fetch
        run: |
          git config --global user.name "github-action"
          git config --global user.email "benchmarks@artipie.com"
          git fetch origin
          git switch -C master origin/master
      - name: Create pull request
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/artipie/artipie/pulls \
            -d '{"head":"head","base":"master","title":"bench: results of benchmarks for version ${{ env.TAG }}"}'
