name: Run benchmarks
#on:
#  push:
#    tags:
#      - 'v*'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Run benchmark
    runs-on: [self-hosted, bench]
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set env
        run: |
          echo "TAG=v0.0.0" >> $GITHUB_ENV
          echo "REPO=helm" >> $GITHUB_ENV
          echo "http_proxy=http://localhost:3128" >> $GITHUB_ENV
          echo "https_proxy=http://localhost:3128" >> $GITHUB_ENV
      - name: Run target benchmark
        run: |
          git clone https://github.com/artipie/benchmarks.git tmp-bench
          cd tmp-bench/adapters
          mkdir -p $GITHUB_WORKSPACE/benchmarks/results/${{ env.TAG }}
          mkdir -p out/${{ env.REPO }}
          echo "tmp_one" > out/${{ env.REPO }}/first.txt
          echo "tmp_two" > out/${{ env.REPO }}/second.txt
          cp -avr out/${{ env.REPO }}/* $GITHUB_WORKSPACE/benchmarks/results/${{ env.TAG }}
          cd ../..
          rm -rf tmp-bench
#          make run TARGET=${{ env.REPO }}
      - name: Commit and push results
        run: |
          git config --global user.name "github-action"
          git config --global user.email "benchmarks@artipie.com"
          git status
          git add .
          git commit -m "bench: added results of benchmarks to readme (through action)"
          git push
